# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z35hTcnxCXXx98odRyeVlwfCKre9lBjq

### Previo a limpiar los datos
"""

# Importamos la librería que usaremos para leer y limpiar los datos
import pandas as pd

"""Leemos la base de datos y la guardamos en la variable 'data_base':"""

# La función 'read_csv' lee la info del database y la guarda en una variable
data_base = pd.read_csv('Plasticos_emitidos_al_oceano.csv')
data_base

"""Para mejorar el entendimiento de los datos, traduciremos los nombres de cada columna:"""

# La columna 'Entity' pasa a ser 'Pais'
data_base = data_base.rename(columns = {'Entity': 'Pais'})

# La columna 'Code' pasa a ser 'sigla'
data_base = data_base.rename(columns = {'Code': 'Sigla'})

# La columna 'Year' pasa a ser 'año'
data_base = data_base.rename(columns = {'Year': 'Año'})

# La columna 'Share of global plastics emitted to ocean' pasa a ser 'Porcentaje mundial de plasticos emitidos al oceano'
data_base = data_base.rename(columns = {'Share of global plastics emitted to ocean': 'Plásticos emitidos al océano mundialmente (%)'})

#La columna 'Mismanaged plastic waste to ocean per capita (kg per year)' pasa Residuos plasticos mal gestionados que llegan al oceano'
data_base = data_base.rename(columns = {'Mismanaged plastic waste to ocean per capita (kg per year)': 'Plásticos emitidos al océano per capita (Kg por año)'})

# La columna 'GDP per capita, PPP (constant 2017 international $)'
data_base = data_base.rename(columns = {'GDP per capita, PPP (constant 2017 international $)': 'PIB per capita'})

# La columna 'Continent' pasa a ser 'Continente'
data_base = data_base.rename(columns = {'Continent': 'Continente'})

data_base

"""### Limpieza de datos

Primero, podemos ver que la columna 'Año' tiene el mismo valor ('2019') en todas las filas:
"""

# La función 'unique()' entrega el listado de valores únicos de la columna
data_base['Año'].unique()

"""Por lo tanto, está columna no aporta información (es redudante). Procedemos a eliminarla de la base de datos:"""

# La función 'drop' con 'axis = 1' elimina la columna que se le entrega
data_base = data_base.drop('Año', axis = 1)
data_base

"""Veamos cuántos datos nulos hay en la base de datos:"""

# La función 'isnull().sum()' entrega el n° de datos nulos en cada columna
data_base.isnull().sum()

"""Podemos ver que la columna 'Continente' tiene todos sus datos nulos:"""

#  La función 'unique()' entrega el listado de valores únicos de la columna
data_base['Continente'].unique()

"""Por lo tanto, no aporta información. Procedemos a eliminarla de la base de datos:"""

# La función 'drop' con 'axis = 1' elimina la columna que se le entrega
data_base = data_base.drop('Continente', axis=1)
data_base

"""Ahora veamos qué países no tienen información en la columna 'Sigla':"""

# Con esto podemos ver qué filas no tienen esta información
data_base[data_base['Sigla'].isnull()]

"""Podemos ver que las filas que no tienen está información corresponden a continentes o zonas geográficas.

Ahora veamos qué países no tienen información en la columna 'PIB per capita':
"""

# Con esto podemos ver qué filas no tienen esta información
data_base[data_base['PIB per capita'].isnull()]

"""Se puede ver que, en este caso, nuevamente la gran mayoría corresponde a continentes o zonas geográficas (como Europa, Asia, Norte América, entre otros), cuyos países ya se encuentran representados en otras filas. Por lo tanto, no aportan información muy relevante a los datos.

Como las filas que tienen datos nulos en la columna 'Sigla' están contenidas en el grupo de filas que tienen datos nulos en la columna 'PIB per capita', eliminamos las filas nulas de este último grupo:
"""

# La función 'dropna()' elimina las filas con datos nulos
# En este caso, para 'Sigla' y 'PIB per capita'
data_base = data_base.dropna()
data_base

"""Revisamos que efectivamente no queden datos nulos:"""

# La función 'isnull().sum()' entrega el n° de datos nulos en cada columna
data_base.isnull().sum()

"""Con esto, obtenemos una base de datos limpia y sin valores nulos."""